name: spp_webview
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  another_flutter_splash_screen: ^1.2.1
  carousel_slider: ^5.0.0
  country_flags: ^3.0.0
  cupertino_icons: ^1.0.8
  crop_image: ^1.0.15
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_image_compress: ^2.3.0
  flutter_native_splash: ^2.4.3
  flutter_svg: ^2.0.16
  http: ^1.2.2
  gap: ^3.0.1
  get: ^4.6.6
  intl: ^0.20.1
  image_picker: ^1.1.2
  markdown_widget: ^2.3.2+6
  url_launcher: ^6.3.1
  pinput: ^5.0.0
  storage_database: ^1.0.7+9
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lang/
    - assets/svg/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
