class Countries {
  static Stream<Map<String, Map<String, String>>> stream() async* {
    Map<String, Map<String, String>> items = {};
    for (String key in all.keys) {
      items[key] = all[key]!;

      yield items;

      await Future.delayed(const Duration(milliseconds: 5));
    }
  }

  static const Map<String, Map<String, String>> all = {
    "AD": {"code": "AD", "name": "Andorra", "call_code": "+376"},
    "AE": {"code": "AE", "name": "United Arab Emirates", "call_code": "+971"},
    "AF": {"code": "AF", "name": "Afghanistan", "call_code": "+93"},
    "AG": {"code": "AG", "name": "Antigua and Barbuda", "call_code": "+1268"},
    "AI": {"code": "AI", "name": "Anguilla", "call_code": "+1264"},
    "AL": {"code": "AL", "name": "Albania", "call_code": "+355"},
    "AM": {"code": "AM", "name": "Armenia", "call_code": "+374"},
    "AO": {"code": "AO", "name": "Angola", "call_code": "+244"},
    "AQ": {"code": "AQ", "name": "Antarctica", "call_code": "N/A"},
    "AR": {"code": "AR", "name": "Argentina", "call_code": "+54"},
    "AS": {"code": "AS", "name": "American Samoa", "call_code": "+1684"},
    "AT": {"code": "AT", "name": "Austria", "call_code": "+43"},
    "AU": {"code": "AU", "name": "Australia", "call_code": "+61"},
    "AW": {"code": "AW", "name": "Aruba", "call_code": "+297"},
    "AX": {"code": "AX", "name": "\u00c5land Islands", "call_code": "+35818"},
    "AZ": {"code": "AZ", "name": "Azerbaijan", "call_code": "+994"},
    "BA": {"code": "BA", "name": "Bosnia and Herzegovina", "call_code": "+387"},
    "BB": {"code": "BB", "name": "Barbados", "call_code": "+1246"},
    "BD": {"code": "BD", "name": "Bangladesh", "call_code": "+880"},
    "BE": {"code": "BE", "name": "Belgium", "call_code": "+32"},
    "BF": {"code": "BF", "name": "Burkina Faso", "call_code": "+226"},
    "BG": {"code": "BG", "name": "Bulgaria", "call_code": "+359"},
    "BH": {"code": "BH", "name": "Bahrain", "call_code": "+973"},
    "BI": {"code": "BI", "name": "Burundi", "call_code": "+257"},
    "BJ": {"code": "BJ", "name": "Benin", "call_code": "+229"},
    "BL": {"code": "BL", "name": "Saint Barth\u00e9lemy", "call_code": "+590"},
    "BM": {"code": "BM", "name": "Bermuda", "call_code": "+1441"},
    "BN": {"code": "BN", "name": "Brunei", "call_code": "+673"},
    "BO": {"code": "BO", "name": "Bolivia", "call_code": "+591"},
    "BQ": {"code": "BQ", "name": "Caribbean Netherlands", "call_code": "+599"},
    "BR": {"code": "BR", "name": "Brazil", "call_code": "+55"},
    "BS": {"code": "BS", "name": "Bahamas", "call_code": "+1242"},
    "BT": {"code": "BT", "name": "Bhutan", "call_code": "+975"},
    "BV": {"code": "BV", "name": "Bouvet Island", "call_code": "+47"},
    "BW": {"code": "BW", "name": "Botswana", "call_code": "+267"},
    "BY": {"code": "BY", "name": "Belarus", "call_code": "+375"},
    "BZ": {"code": "BZ", "name": "Belize", "call_code": "+501"},
    "CA": {"code": "CA", "name": "Canada", "call_code": "+1"},
    "CC": {"code": "CC", "name": "Cocos (Keeling) Islands", "call_code": "+61"},
    "CD": {"code": "CD", "name": "DR Congo", "call_code": "+243"},
    "CF": {
      "code": "CF",
      "name": "Central African Republic",
      "call_code": "+236"
    },
    "CG": {"code": "CG", "name": "Republic of the Congo", "call_code": "+242"},
    "CH": {"code": "CH", "name": "Switzerland", "call_code": "+41"},
    "CI": {"code": "CI", "name": "Ivory Coast", "call_code": "+225"},
    "CK": {"code": "CK", "name": "Cook Islands", "call_code": "+682"},
    "CL": {"code": "CL", "name": "Chile", "call_code": "+56"},
    "CM": {"code": "CM", "name": "Cameroon", "call_code": "+237"},
    "CN": {"code": "CN", "name": "China", "call_code": "+86"},
    "CO": {"code": "CO", "name": "Colombia", "call_code": "+57"},
    "CR": {"code": "CR", "name": "Costa Rica", "call_code": "+506"},
    "CU": {"code": "CU", "name": "Cuba", "call_code": "+53"},
    "CV": {"code": "CV", "name": "Cape Verde", "call_code": "+238"},
    "CW": {"code": "CW", "name": "Cura\u00e7ao", "call_code": "+599"},
    "CX": {"code": "CX", "name": "Christmas Island", "call_code": "+61"},
    "CY": {"code": "CY", "name": "Cyprus", "call_code": "+357"},
    "CZ": {"code": "CZ", "name": "Czechia", "call_code": "+420"},
    "DE": {"code": "DE", "name": "Germany", "call_code": "+49"},
    "DJ": {"code": "DJ", "name": "Djibouti", "call_code": "+253"},
    "DK": {"code": "DK", "name": "Denmark", "call_code": "+45"},
    "DM": {"code": "DM", "name": "Dominica", "call_code": "+1767"},
    "DO": {"code": "DO", "name": "Dominican Republic", "call_code": "+1809"},
    "DZ": {"code": "DZ", "name": "Algeria", "call_code": "+213"},
    "EC": {"code": "EC", "name": "Ecuador", "call_code": "+593"},
    "EE": {"code": "EE", "name": "Estonia", "call_code": "+372"},
    "EG": {"code": "EG", "name": "Egypt", "call_code": "+20"},
    "EH": {"code": "EH", "name": "Western Sahara", "call_code": "+2125288"},
    "ER": {"code": "ER", "name": "Eritrea", "call_code": "+291"},
    "ES": {"code": "ES", "name": "Spain", "call_code": "+34"},
    "ET": {"code": "ET", "name": "Ethiopia", "call_code": "+251"},
    "FI": {"code": "FI", "name": "Finland", "call_code": "+358"},
    "FJ": {"code": "FJ", "name": "Fiji", "call_code": "+679"},
    "FK": {"code": "FK", "name": "Falkland Islands", "call_code": "+500"},
    "FM": {"code": "FM", "name": "Micronesia", "call_code": "+691"},
    "FO": {"code": "FO", "name": "Faroe Islands", "call_code": "+298"},
    "FR": {"code": "FR", "name": "France", "call_code": "+33"},
    "GA": {"code": "GA", "name": "Gabon", "call_code": "+241"},
    "GB": {"code": "GB", "name": "United Kingdom", "call_code": "+44"},
    "GD": {"code": "GD", "name": "Grenada", "call_code": "+1473"},
    "GE": {"code": "GE", "name": "Georgia", "call_code": "+995"},
    "GF": {"code": "GF", "name": "French Guiana", "call_code": "+594"},
    "GG": {"code": "GG", "name": "Guernsey", "call_code": "+44"},
    "GH": {"code": "GH", "name": "Ghana", "call_code": "+233"},
    "GI": {"code": "GI", "name": "Gibraltar", "call_code": "+350"},
    "GL": {"code": "GL", "name": "Greenland", "call_code": "+299"},
    "GM": {"code": "GM", "name": "Gambia", "call_code": "+220"},
    "GN": {"code": "GN", "name": "Guinea", "call_code": "+224"},
    "GP": {"code": "GP", "name": "Guadeloupe", "call_code": "+590"},
    "GQ": {"code": "GQ", "name": "Equatorial Guinea", "call_code": "+240"},
    "GR": {"code": "GR", "name": "Greece", "call_code": "+30"},
    "GS": {"code": "GS", "name": "South Georgia", "call_code": "+500"},
    "GT": {"code": "GT", "name": "Guatemala", "call_code": "+502"},
    "GU": {"code": "GU", "name": "Guam", "call_code": "+1671"},
    "GW": {"code": "GW", "name": "Guinea-Bissau", "call_code": "+245"},
    "GY": {"code": "GY", "name": "Guyana", "call_code": "+592"},
    "HK": {"code": "HK", "name": "Hong Kong", "call_code": "+852"},
    "HM": {
      "code": "HM",
      "name": "Heard Island and McDonald Islands",
      "call_code": "N/A"
    },
    "HN": {"code": "HN", "name": "Honduras", "call_code": "+504"},
    "HR": {"code": "HR", "name": "Croatia", "call_code": "+385"},
    "HT": {"code": "HT", "name": "Haiti", "call_code": "+509"},
    "HU": {"code": "HU", "name": "Hungary", "call_code": "+36"},
    "ID": {"code": "ID", "name": "Indonesia", "call_code": "+62"},
    "IE": {"code": "IE", "name": "Ireland", "call_code": "+353"},
    "IM": {"code": "IM", "name": "Isle of Man", "call_code": "+44"},
    "IN": {"code": "IN", "name": "India", "call_code": "+91"},
    "IO": {
      "code": "IO",
      "name": "British Indian Ocean Territory",
      "call_code": "+246"
    },
    "IQ": {"code": "IQ", "name": "Iraq", "call_code": "+964"},
    "IR": {"code": "IR", "name": "Iran", "call_code": "+98"},
    "IS": {"code": "IS", "name": "Iceland", "call_code": "+354"},
    "IT": {"code": "IT", "name": "Italy", "call_code": "+39"},
    "JE": {"code": "JE", "name": "Jersey", "call_code": "+44"},
    "JM": {"code": "JM", "name": "Jamaica", "call_code": "+1876"},
    "JO": {"code": "JO", "name": "Jordan", "call_code": "+962"},
    "JP": {"code": "JP", "name": "Japan", "call_code": "+81"},
    "KE": {"code": "KE", "name": "Kenya", "call_code": "+254"},
    "KG": {"code": "KG", "name": "Kyrgyzstan", "call_code": "+996"},
    "KH": {"code": "KH", "name": "Cambodia", "call_code": "+855"},
    "KI": {"code": "KI", "name": "Kiribati", "call_code": "+686"},
    "KM": {"code": "KM", "name": "Comoros", "call_code": "+269"},
    "KN": {"code": "KN", "name": "Saint Kitts and Nevis", "call_code": "+1869"},
    "KP": {"code": "KP", "name": "North Korea", "call_code": "+850"},
    "KR": {"code": "KR", "name": "South Korea", "call_code": "+82"},
    "KW": {"code": "KW", "name": "Kuwait", "call_code": "+965"},
    "KY": {"code": "KY", "name": "Cayman Islands", "call_code": "+1345"},
    "KZ": {"code": "KZ", "name": "Kazakhstan", "call_code": "+76"},
    "LA": {"code": "LA", "name": "Laos", "call_code": "+856"},
    "LB": {"code": "LB", "name": "Lebanon", "call_code": "+961"},
    "LC": {"code": "LC", "name": "Saint Lucia", "call_code": "+1758"},
    "LI": {"code": "LI", "name": "Liechtenstein", "call_code": "+423"},
    "LK": {"code": "LK", "name": "Sri Lanka", "call_code": "+94"},
    "LR": {"code": "LR", "name": "Liberia", "call_code": "+231"},
    "LS": {"code": "LS", "name": "Lesotho", "call_code": "+266"},
    "LT": {"code": "LT", "name": "Lithuania", "call_code": "+370"},
    "LU": {"code": "LU", "name": "Luxembourg", "call_code": "+352"},
    "LV": {"code": "LV", "name": "Latvia", "call_code": "+371"},
    "LY": {"code": "LY", "name": "Libya", "call_code": "+218"},
    "MA": {"code": "MA", "name": "Morocco", "call_code": "+212"},
    "MC": {"code": "MC", "name": "Monaco", "call_code": "+377"},
    "MD": {"code": "MD", "name": "Moldova", "call_code": "+373"},
    "ME": {"code": "ME", "name": "Montenegro", "call_code": "+382"},
    "MF": {"code": "MF", "name": "Saint Martin", "call_code": "+590"},
    "MG": {"code": "MG", "name": "Madagascar", "call_code": "+261"},
    "MH": {"code": "MH", "name": "Marshall Islands", "call_code": "+692"},
    "MK": {"code": "MK", "name": "North Macedonia", "call_code": "+389"},
    "ML": {"code": "ML", "name": "Mali", "call_code": "+223"},
    "MM": {"code": "MM", "name": "Myanmar", "call_code": "+95"},
    "MN": {"code": "MN", "name": "Mongolia", "call_code": "+976"},
    "MO": {"code": "MO", "name": "Macau", "call_code": "+853"},
    "MP": {
      "code": "MP",
      "name": "Northern Mariana Islands",
      "call_code": "+1670"
    },
    "MQ": {"code": "MQ", "name": "Martinique", "call_code": "+596"},
    "MR": {"code": "MR", "name": "Mauritania", "call_code": "+222"},
    "MS": {"code": "MS", "name": "Montserrat", "call_code": "+1664"},
    "MT": {"code": "MT", "name": "Malta", "call_code": "+356"},
    "MU": {"code": "MU", "name": "Mauritius", "call_code": "+230"},
    "MV": {"code": "MV", "name": "Maldives", "call_code": "+960"},
    "MW": {"code": "MW", "name": "Malawi", "call_code": "+265"},
    "MX": {"code": "MX", "name": "Mexico", "call_code": "+52"},
    "MY": {"code": "MY", "name": "Malaysia", "call_code": "+60"},
    "MZ": {"code": "MZ", "name": "Mozambique", "call_code": "+258"},
    "NA": {"code": "NA", "name": "Namibia", "call_code": "+264"},
    "NC": {"code": "NC", "name": "New Caledonia", "call_code": "+687"},
    "NE": {"code": "NE", "name": "Niger", "call_code": "+227"},
    "NF": {"code": "NF", "name": "Norfolk Island", "call_code": "+672"},
    "NG": {"code": "NG", "name": "Nigeria", "call_code": "+234"},
    "NI": {"code": "NI", "name": "Nicaragua", "call_code": "+505"},
    "NL": {"code": "NL", "name": "Netherlands", "call_code": "+31"},
    "NO": {"code": "NO", "name": "Norway", "call_code": "+47"},
    "NP": {"code": "NP", "name": "Nepal", "call_code": "+977"},
    "NR": {"code": "NR", "name": "Nauru", "call_code": "+674"},
    "NU": {"code": "NU", "name": "Niue", "call_code": "+683"},
    "NZ": {"code": "NZ", "name": "New Zealand", "call_code": "+64"},
    "OM": {"code": "OM", "name": "Oman", "call_code": "+968"},
    "PA": {"code": "PA", "name": "Panama", "call_code": "+507"},
    "PE": {"code": "PE", "name": "Peru", "call_code": "+51"},
    "PF": {"code": "PF", "name": "French Polynesia", "call_code": "+689"},
    "PG": {"code": "PG", "name": "Papua New Guinea", "call_code": "+675"},
    "PH": {"code": "PH", "name": "Philippines", "call_code": "+63"},
    "PK": {"code": "PK", "name": "Pakistan", "call_code": "+92"},
    "PL": {"code": "PL", "name": "Poland", "call_code": "+48"},
    "PM": {
      "code": "PM",
      "name": "Saint Pierre and Miquelon",
      "call_code": "+508"
    },
    "PN": {"code": "PN", "name": "Pitcairn Islands", "call_code": "+64"},
    "PR": {"code": "PR", "name": "Puerto Rico", "call_code": "+1787"},
    "PS": {"code": "PS", "name": "Palestine", "call_code": "+970"},
    "PT": {"code": "PT", "name": "Portugal", "call_code": "+351"},
    "PW": {"code": "PW", "name": "Palau", "call_code": "+680"},
    "PY": {"code": "PY", "name": "Paraguay", "call_code": "+595"},
    "QA": {"code": "QA", "name": "Qatar", "call_code": "+974"},
    "RE": {"code": "RE", "name": "R\u00e9union", "call_code": "+262"},
    "RO": {"code": "RO", "name": "Romania", "call_code": "+40"},
    "RS": {"code": "RS", "name": "Serbia", "call_code": "+381"},
    "RU": {"code": "RU", "name": "Russia", "call_code": "+73"},
    "RW": {"code": "RW", "name": "Rwanda", "call_code": "+250"},
    "SA": {"code": "SA", "name": "Saudi Arabia", "call_code": "+966"},
    "SB": {"code": "SB", "name": "Solomon Islands", "call_code": "+677"},
    "SC": {"code": "SC", "name": "Seychelles", "call_code": "+248"},
    "SD": {"code": "SD", "name": "Sudan", "call_code": "+249"},
    "SE": {"code": "SE", "name": "Sweden", "call_code": "+46"},
    "SG": {"code": "SG", "name": "Singapore", "call_code": "+65"},
    "SH": {
      "code": "SH",
      "name": "Saint Helena, Ascension and Tristan da Cunha",
      "call_code": "+290"
    },
    "SI": {"code": "SI", "name": "Slovenia", "call_code": "+386"},
    "SJ": {
      "code": "SJ",
      "name": "Svalbard and Jan Mayen",
      "call_code": "+4779"
    },
    "SK": {"code": "SK", "name": "Slovakia", "call_code": "+421"},
    "SL": {"code": "SL", "name": "Sierra Leone", "call_code": "+232"},
    "SM": {"code": "SM", "name": "San Marino", "call_code": "+378"},
    "SN": {"code": "SN", "name": "Senegal", "call_code": "+221"},
    "SO": {"code": "SO", "name": "Somalia", "call_code": "+252"},
    "SR": {"code": "SR", "name": "Suriname", "call_code": "+597"},
    "SS": {"code": "SS", "name": "South Sudan", "call_code": "+211"},
    "ST": {
      "code": "ST",
      "name": "S\u00e3o Tom\u00e9 and Pr\u00edncipe",
      "call_code": "+239"
    },
    "SV": {"code": "SV", "name": "El Salvador", "call_code": "+503"},
    "SX": {"code": "SX", "name": "Sint Maarten", "call_code": "+1721"},
    "SY": {"code": "SY", "name": "Syria", "call_code": "+963"},
    "SZ": {"code": "SZ", "name": "Eswatini", "call_code": "+268"},
    "TC": {
      "code": "TC",
      "name": "Turks and Caicos Islands",
      "call_code": "+1649"
    },
    "TD": {"code": "TD", "name": "Chad", "call_code": "+235"},
    "TF": {
      "code": "TF",
      "name": "French Southern and Antarctic Lands",
      "call_code": "+262"
    },
    "TG": {"code": "TG", "name": "Togo", "call_code": "+228"},
    "TH": {"code": "TH", "name": "Thailand", "call_code": "+66"},
    "TJ": {"code": "TJ", "name": "Tajikistan", "call_code": "+992"},
    "TK": {"code": "TK", "name": "Tokelau", "call_code": "+690"},
    "TL": {"code": "TL", "name": "Timor-Leste", "call_code": "+670"},
    "TM": {"code": "TM", "name": "Turkmenistan", "call_code": "+993"},
    "TN": {"code": "TN", "name": "Tunisia", "call_code": "+216"},
    "TO": {"code": "TO", "name": "Tonga", "call_code": "+676"},
    "TR": {"code": "TR", "name": "Turkey", "call_code": "+90"},
    "TT": {"code": "TT", "name": "Trinidad and Tobago", "call_code": "+1868"},
    "TV": {"code": "TV", "name": "Tuvalu", "call_code": "+688"},
    "TW": {"code": "TW", "name": "Taiwan", "call_code": "+886"},
    "TZ": {"code": "TZ", "name": "Tanzania", "call_code": "+255"},
    "UA": {"code": "UA", "name": "Ukraine", "call_code": "+380"},
    "UG": {"code": "UG", "name": "Uganda", "call_code": "+256"},
    "UM": {
      "code": "UM",
      "name": "United States Minor Outlying Islands",
      "call_code": "+268"
    },
    "US": {"code": "US", "name": "United States", "call_code": "+1201"},
    "UY": {"code": "UY", "name": "Uruguay", "call_code": "+598"},
    "UZ": {"code": "UZ", "name": "Uzbekistan", "call_code": "+998"},
    "VA": {"code": "VA", "name": "Vatican City", "call_code": "+3906698"},
    "VC": {
      "code": "VC",
      "name": "Saint Vincent and the Grenadines",
      "call_code": "+1784"
    },
    "VE": {"code": "VE", "name": "Venezuela", "call_code": "+58"},
    "VG": {
      "code": "VG",
      "name": "British Virgin Islands",
      "call_code": "+1284"
    },
    "VI": {
      "code": "VI",
      "name": "United States Virgin Islands",
      "call_code": "+1340"
    },
    "VN": {"code": "VN", "name": "Vietnam", "call_code": "+84"},
    "VU": {"code": "VU", "name": "Vanuatu", "call_code": "+678"},
    "WF": {"code": "WF", "name": "Wallis and Futuna", "call_code": "+681"},
    "WS": {"code": "WS", "name": "Samoa", "call_code": "+685"},
    "XK": {"code": "XK", "name": "Kosovo", "call_code": "+383"},
    "YE": {"code": "YE", "name": "Yemen", "call_code": "+967"},
    "YT": {"code": "YT", "name": "Mayotte", "call_code": "+262"},
    "ZA": {"code": "ZA", "name": "South Africa", "call_code": "+27"},
    "ZM": {"code": "ZM", "name": "Zambia", "call_code": "+260"},
    "ZW": {"code": "ZW", "name": "Zimbabwe", "call_code": "+263"}
  };
}
